/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_prajaram_jni_JNISample */

#ifndef _Included_com_prajaram_jni_JNISample
#define _Included_com_prajaram_jni_JNISample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_prajaram_jni_JNISample
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_prajaram_jni_JNISample_intMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_prajaram_jni_JNISample
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_prajaram_jni_JNISample_booleanMethod
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_prajaram_jni_JNISample
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_prajaram_jni_JNISample_stringMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_prajaram_jni_JNISample
 * Method:    intArrayMethod
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_prajaram_jni_JNISample_intArrayMethod
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
